- name: Install sudo
  ansible.builtin.apt:
    name:
      - sudo
    state: latest

- name: Create group
  ansible.builtin.group:
    name: "{{ item.group }}"
    state: present
  loop: "{{ users }}"

- name: Create user
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups | default(omit) }}"
    shell: "{{ item.shell }}"
    # min. Ansible 2.12
    # umask: "007"
    state: present
    # Always update password!
    password: "{{ item.password | string | password_hash('sha512') }}"
    password_lock: false
  loop: "{{ users }}"

- name: Create /home/.ssh dir
  ansible.builtin.file:
    path:  "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: '0750'
  loop: "{{ users }}"

- name: Synchronize public keys for the user
  ansible.builtin.lineinfile:
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    create: yes
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    line: "{{ item.public }}"
    state: present
  loop: "{{ users }}"
  when: item.public is defined

- name: Set up password-less sudo for "sudo" group
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo ALL='
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: Update root password
  ansible.builtin.user:
    name: root
    password: "{{ root_password | string | password_hash('sha512') }}"
    state: present
