- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  register: apt_action
  until: >
    apt_action is success 
    or ('Failed to lock apt for exclusive operation' not in apt_action.msg and 
    '/var/lib/dpkg/lock' not in apt_action.msg)
  retries: 3
  delay: 5

- name: Install or update openssh-server
  ansible.builtin.apt:
    state: latest
    pkg:
      - openssh-server
  until: >
    apt_action is success 
    or ('Failed to lock apt for exclusive operation' not in apt_action.msg 
    and '/var/lib/dpkg/lock' not in apt_action.msg)
  retries: 3
  delay: 5

- name: Create /run/sshd directory
  ansible.builtin.file:
    path: "/run/sshd"
    owner: root
    group: root
    state: directory
    mode: '0750'

- name: Configure openssh-server
  ansible.builtin.template:
    src: sshd_conf.j2
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify: Restart sshd
